#!/bin/bash
dir="$(cd "$(dirname "$0")" && pwd)"
cd $dir
set -e

echo "Step 1 of 3: Downloading..."
sleep 1
script/download

echo "Step 2 of 3: Building..."
sleep 1
script/build

echo "Step 3 of 3: Flashing..."
sleep 1
script/flash

echo "LogBox-HAT is now running the new software!"